import type { Maker, Product } from "../backend.d";

export const SEED_MAKERS: Omit<Maker, "id">[] = [
  {
    name: "Anju Choudhary",
    state: "Bihar",
    bio: "Bihar ki dharti ki khushboo — Anju ji 30 saalon se apni daadi ki recipes ko zinda rakh rahi hain. Unka makhana namkeen aur tilkut poori Bihar mein mashhoor hai.",
    story:
      "Muzaffarpur ki galiyon mein pali-badhi Anju Choudhary ji ne apni naani se seekhe nuskhon ko aaj ek rozgaar banaya hai. Teeno bachche aur pati ke saath milke woh har weekend pure dil se khaana banati hain — ek ek masala haath se chuna jaata hai, koi machine nahin, koi shortcut nahin. Unka sapna hai ki Bihar ka swaad puri duniya tak pahunche.",
    photoUrl: "",
    whatsappNumber: "+91-9883140470",
    isActive: true,
  },
  {
    name: "Babita Tai",
    state: "Haryana",
    bio: "Rohtak ki Babita Tai ki mathri aur churma ladoo khane wale ek baar kha kar bhool nahin paate. 25 saal ka anubhav aur haath ka jaadu — sab milke ek baat bolte hain: Ghar jaisa swaad!",
    story:
      "Babita Tai ne apni saas ke haathon se seekha khana banana. Aaj unke do bete bhi unka kaam dekhte hain. Rohtak ke pados mein unka ghar hi unki workshop hai — subah 4 baje uthke ghee garam karna, taze gehun peesna — yahi unki zindagi hai. Jab log order dete hain toh woh kehti hain: Beta, ruk jaana, dil se banaungi.",
    photoUrl: "",
    whatsappNumber: "+91-9883140470",
    isActive: true,
  },
  {
    name: "Sarla Maasi",
    state: "Uttar Pradesh",
    bio: "Lucknow ki Sarla Maasi UP ki nawabi rasoi ki waaris hain. Petha, nimbu achar aur besan ladoo — unka har product ek nawaabi swaad le ke aata hai. 35 saal ka tajurba.",
    story:
      "Sarla Maasi ko Lucknow ke Hazratganj se bada love milta hai. Unke haath ka petha aur gajar ka halwa poore mohalle mein famous hai. Unhone kabhi socha bhi nahin tha ki ghar ka khaana kamaai ka zariya ban sakta hai — aaj unki beti bhi unke saath khadi hai, sikha rahi hain agli peedhi ko yeh kalakariyaan.",
    photoUrl: "",
    whatsappNumber: "+91-9883140470",
    isActive: true,
  },
  {
    name: "Preetkaur Aunty",
    state: "Punjab",
    bio: "Amritsar se Preetkaur ji — Punjabi rasoi ki shaan. Unka aam ka achar, gajak aur pinni Waheguru ji ki kirpa se bana lagta hai. Poore mohalle mein unhe 'Achar Wali Aunty' kehte hain.",
    story:
      "Preetkaur ji ke haathon mein jo swaad hai, woh teen peedhiyon ki mehnat ka fal hai. Nani se naani, naani se maa, maa se Preetkaur — recipes sirf likh nahin deta, haath se seekhi jaati hain. Unka mango pickle Amritsar se Delhi tak order hota hai. Aaj woh apni naatins ko bhi sikhana chahti hain — taaki yeh dastaan aur aage bade.",
    photoUrl: "",
    whatsappNumber: "+91-9883140470",
    isActive: true,
  },
  {
    name: "Geeta Devi",
    state: "Uttarakhand",
    bio: "Almora pahaadon ki Geeta Devi ji — Pahadi rasoi ki asli waris. Buransh ka sharbat, jhangora ki kheer aur timru pickle jo pahaadon se seedha aapke ghar aata hai.",
    story:
      "Geeta Devi ko unka gaon Almora chhodna kabhi pasand nahin tha. Pahad ki mitti, nadiya ka paani, jungle ke masale — yehi unka khazana hai. Jab unka buransh ka sharbat pehli baar order hua Delhi mein, toh unki aankhon mein aansu aa gaye — khushi ke. Aaj unke saath poore gaon ki kuch auraten bhi kaam karti hain. Pahaadi khushboo ab desh bhar pahunch rahi hai.",
    photoUrl: "",
    whatsappNumber: "+91-9883140470",
    isActive: true,
  },
];

// Products mapped by maker index (0-4 matching SEED_MAKERS order)
// makerIndex: 0=Anju(Bihar), 1=Babita(Haryana), 2=Sarla(UP), 3=Preetkaur(Punjab), 4=Geeta(Uttarakhand)
export type Season = "winter" | "summer" | "monsoon" | "spring" | "all-season";

export type AvailabilityType =
  | "available-today"
  | "pre-order"
  | "seasonal"
  | "festival-special";

export type SeedProduct = Omit<Product, "id" | "makerId"> & {
  makerIndex: number;
  season: Season;
  availability: AvailabilityType;
};

export const SEED_PRODUCTS: SeedProduct[] = [
  // ============================================================
  // BIHAR — 10 Products (makerIndex: 0 = Anju Choudhary)
  // ============================================================
  {
    makerIndex: 0,
    name: "Aam Ka Achar (Bihari Style)",
    description:
      "Muzaffarpur ki kacchi keri se bana yeh achar — sarson ke tel mein bhiga, dhoop mein sookha, haath se bana. Dadi ke zamaane ka asli swaad. Har bite mein Bihar ki yaad.",
    ingredients: [
      "Kacchi Keri (Raw Mango)",
      "Sarson ka Tel (Mustard Oil)",
      "Methi Dana (Fenugreek)",
      "Haldi (Turmeric)",
      "Lal Mirch (Red Chili)",
      "Kala Namak",
      "Saunf (Fennel)",
    ],
    preparationMethod:
      "Mangoes hand-cut, sun-dried for 3 days, then slow-marinated in pure mustard oil with whole spices for 21 days. No vinegar, no preservatives. Ready in 3 weeks.",
    usp: "Zero chemical, zero preservative. Mustard oil pressed fresh in-house. Keri sourced directly from Muzaffarpur mango belt — same trees, every season.",
    mrp: 220,
    sellingPrice: 170,
    minBatchKg: 5,
    category: "achar",
    state: "Bihar",
    season: "summer",
    availability: "seasonal",
    imageUrl: "/assets/generated/product-achar.dim_600x500.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 0,
    name: "Tilkut (Gaya Special)",
    description:
      "Gaya ka tilkut — til aur gurh se bana yeh mithaas sirf Gaya mein milti thi. Ab Anju ji ne isse ghar tak pahunchaya. Dasharath Mandir ke prasaad jaisi feeling!",
    ingredients: [
      "Til (White Sesame)",
      "Gurh (Jaggery)",
      "Elaichi (Cardamom)",
      "Pure Ghee",
    ],
    preparationMethod:
      "Sesame roasted on iron pan, jaggery melted slowly, mixed while hot and pressed into traditional molds. Cooled overnight, hand-cut into pieces.",
    usp: "Made in exact ratio of Gaya temple prasad tradition. Til sourced from Bihar farms. 100% natural sweetener — pure jaggery, no refined sugar.",
    mrp: 280,
    sellingPrice: 220,
    minBatchKg: 3,
    category: "sweets",
    state: "Bihar",
    season: "winter",
    availability: "festival-special",
    imageUrl: "/assets/generated/product-tilkut-bihar.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 0,
    name: "Sattu ka Ladoo",
    description:
      "Bihar ka protein bomb — bhuney chane ka sattu, gurh aur ghee — teen cheezein aur ek perfect ladoo. Dawai nahi, khana hai. Generations se yahi shakti deta aaya hai.",
    ingredients: [
      "Bhuna Sattu (Roasted Gram Flour)",
      "Gurh (Jaggery)",
      "Ghee (Pure Cow)",
      "Saunf",
      "Ilaychi",
    ],
    preparationMethod:
      "Gram roasted on slow flame for 2 hours. Ground fresh to fine flour. Mixed with melted jaggery and ghee while warm. Hand-rolled into uniform ladoos.",
    usp: "High protein (20g per 100g), naturally energising. Bihar's original health food — eaten by farmers since centuries. No baking powder, no additives.",
    mrp: 240,
    sellingPrice: 190,
    minBatchKg: 3,
    category: "sweets",
    state: "Bihar",
    season: "summer",
    availability: "available-today",
    imageUrl: "/assets/generated/product-sattu-ladoo-bihar.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 0,
    name: "Thekua (Chhath Prasad)",
    description:
      "Chhath Puja ka pavitra prasad — gehun aatta, gurh aur ghee se bana Thekua. Surya devta ko pehle, phir ghar ko. Har bite mein aastan ki khushboo.",
    ingredients: [
      "Gehun Aatta (Whole Wheat Flour)",
      "Gurh (Jaggery)",
      "Ghee",
      "Saunf",
      "Nariyal (Coconut)",
      "Elaichi",
    ],
    preparationMethod:
      "Dough made with jaggery water and ghee. Shaped in traditional wooden press molds. Fried on slow flame in pure ghee until golden and crisp.",
    usp: "Bihar's most sacred snack — made exactly as Chhath Puja tradition demands. No maida. Stone-ground wheat flour only. Stays fresh for 2 weeks.",
    mrp: 180,
    sellingPrice: 140,
    minBatchKg: 3,
    category: "snacks",
    state: "Bihar",
    season: "winter",
    availability: "festival-special",
    imageUrl: "/assets/generated/product-thekua-bihar.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 0,
    name: "Makhana Namkeen (Foxnut Crunch)",
    description:
      "Bihar ka superstar — makhana! Ghee mein seke, namak-mirch chadhake, yeh ek baar kha lo toh band nahin hoga. Healthy guilt-free snacking at its best.",
    ingredients: [
      "Makhana (Foxnut)",
      "Desi Ghee",
      "Rock Salt",
      "Black Pepper",
      "Jeera",
      "Haldi",
    ],
    preparationMethod:
      "Makhana dry-roasted on low flame for 45 mins. Tossed with ghee and spice blend while hot. Cooled slowly for maximum crunch.",
    usp: "Mithila's famous foxnut — Bihar produces 90% of world's makhana. Anti-inflammatory, low calorie. Anju ji sources directly from Darbhanga farmer families.",
    mrp: 320,
    sellingPrice: 260,
    minBatchKg: 2,
    category: "namkeen",
    state: "Bihar",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-makhana-namkeen-bihar.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 0,
    name: "Khaja (Silao Special)",
    description:
      "Silao ka Khaja — layered, flaky, mildly sweet. GI tagged mithaai jo sirf Bihar mein milti thi. Rajgir jaane wale sabse pehle Khaja kharidne ruk jaate hain.",
    ingredients: ["Maida", "Ghee", "Chini (Sugar)", "Elaichi", "Kesar"],
    preparationMethod:
      "Dough layered with ghee 12 times (traditional lamination), cut into shapes, fried slowly, then soaked in sugar syrup and sun-dried.",
    usp: "GI-tagged Bihar delicacy from Silao. Anju ji learnt from a 4th-generation Silao halwai family. Unique layered texture impossible to replicate industrially.",
    mrp: 260,
    sellingPrice: 200,
    minBatchKg: 3,
    category: "sweets",
    state: "Bihar",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-khaja-bihar.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 0,
    name: "Singhara Atta Barfi",
    description:
      "Navratri special — water chestnut flour ki barfi. Fasting mein bhi swaad! Pure singhara aata, ghee aur mishri se bani yeh barfi energy aur taste dono deti hai.",
    ingredients: [
      "Singhara Aata (Water Chestnut Flour)",
      "Desi Ghee",
      "Mishri (Rock Sugar)",
      "Elaichi",
      "Pista",
      "Badam",
    ],
    preparationMethod:
      "Flour roasted in ghee on slow flame until fragrant. Sugar syrup added, cooked until thickened. Poured on ghee-lined tray, cooled, cut into diamonds.",
    usp: "Vrat-friendly, gluten-free. Singhara flour is cooling and high in energy. Anju ji makes this fresh only for orders — no advance stocking.",
    mrp: 350,
    sellingPrice: 280,
    minBatchKg: 2,
    category: "sweets",
    state: "Bihar",
    season: "winter",
    availability: "pre-order",
    imageUrl: "/assets/generated/product-singhara-barfi-bihar.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 0,
    name: "Laai (Puffed Rice Sweet)",
    description:
      "Makar Sankranti ka yaad — kheel aur til se bana laai. Gur mein chipka, phir seedha dabba mein. Simple mein jo mazaa hai woh kisi cake mein nahin.",
    ingredients: [
      "Murmura (Puffed Rice)",
      "Til (Sesame)",
      "Gurh (Jaggery)",
      "Ghee",
      "Elaichi",
    ],
    preparationMethod:
      "Jaggery melted to soft-ball stage. Puffed rice and sesame tossed in, quickly shaped into bars or balls while warm. Set for 2 hours.",
    usp: "Bihar's Sankranti tradition in a box. Pure jaggery (no sugar), loaded with iron and calcium. Zero maida. Great travel snack for kids.",
    mrp: 160,
    sellingPrice: 120,
    minBatchKg: 3,
    category: "sweets",
    state: "Bihar",
    season: "winter",
    availability: "festival-special",
    imageUrl: "/assets/generated/product-laai-bihar.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 0,
    name: "Chana Jor Garam (Bihari Style)",
    description:
      "Patna station par woh aawaaz — 'Chana Jor Garaaam!' Ab wahi swaad ghar mein. Pressed chickpeas, masale, lemon — teen second mein nostalgia ka blast.",
    ingredients: [
      "Chana (Chickpeas)",
      "Chaat Masala",
      "Kaala Namak",
      "Jeera",
      "Lal Mirch",
      "Amchur",
    ],
    preparationMethod:
      "Chickpeas soaked, partially cooked, then pressed thin on iron griddle. Sun-dried. Spice mix prepared fresh. Tossed before packing.",
    usp: "Protein-rich, low-fat street snack. Bihar railway platform's most iconic taste. No artificial colors. Can be eaten as is or with raw onion and lemon.",
    mrp: 140,
    sellingPrice: 110,
    minBatchKg: 2,
    category: "namkeen",
    state: "Bihar",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-chana-jor-bihar.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 0,
    name: "Anarsa (Rice Sesame Sweet)",
    description:
      "Deepawali ki mithaai — chawal ke aate aur gurh se bana Anarsa. Til jagmagata upar, andar soft aur dense. Ek khaoge toh packet saaf ho jaayega.",
    ingredients: [
      "Chawal ka Aata (Rice Flour)",
      "Gurh (Jaggery)",
      "Til (Sesame)",
      "Ghee",
      "Elaichi",
    ],
    preparationMethod:
      "Rice soaked for 3 days, dried, ground. Mixed with jaggery paste. Shaped in round discs, coated with sesame, shallow fried in ghee on slow flame.",
    usp: "Traditional Bihar Diwali sweet — rarely available commercially. Takes 4 days to prepare. Anju ji uses red rice from Bhagalpur for extra flavour.",
    mrp: 300,
    sellingPrice: 240,
    minBatchKg: 3,
    category: "sweets",
    state: "Bihar",
    season: "winter",
    availability: "festival-special",
    imageUrl: "/assets/generated/product-anarsa-bihar.dim_800x600.jpg",
    isAvailable: true,
  },

  // ============================================================
  // HARYANA — 10 Products (makerIndex: 1 = Babita Tai)
  // ============================================================
  {
    makerIndex: 1,
    name: "Methi Mathri",
    description:
      "Rohtak ki Babita Tai ki haath se bani methi mathri — chai ke saath best companion. Khasta, crispy, aur methi ki khushboo. Ghar ki yaad dilata hai har baar.",
    ingredients: [
      "Gehun Aatta (Whole Wheat)",
      "Methi Patta (Fenugreek Leaves)",
      "Desi Ghee",
      "Ajwain (Carom)",
      "Kaala Namak",
      "Kali Mirch",
    ],
    preparationMethod:
      "Dough made stiff with ghee and ajwain. Methi leaves hand-chopped and added. Rolled thin, pricked with fork. Fried slowly in pure ghee on low flame.",
    usp: "Stone-ground wheat flour. Methi from Babita ji's kitchen garden. No refined oil — pure ghee fried. Stays fresh for 3 weeks without refrigeration.",
    mrp: 180,
    sellingPrice: 140,
    minBatchKg: 3,
    category: "snacks",
    state: "Haryana",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-namakpara.dim_600x500.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 1,
    name: "Churma Ladoo",
    description:
      "Haryana ki shaadi-byah ki mithaai — ghee mein bhuna aatta, gurh ki meethas. Jab ek khao toh doosra haath khud hi uthta hai. Babuji ke haath ka swaad.",
    ingredients: [
      "Gehun Aatta (Whole Wheat Flour)",
      "Gurh (Jaggery)",
      "Desi Ghee",
      "Elaichi",
      "Saunf",
      "Khoya",
    ],
    preparationMethod:
      "Wheat flour slow-roasted in ghee for 1.5 hours until fragrant and golden. Mixed with powdered jaggery and elaichi. Hand-shaped into round ladoos.",
    usp: "100% jaggery sweetened — no sugar, no preservatives. Babita ji's churma uses 40-year-old family ratio of ghee to flour for perfect texture.",
    mrp: 260,
    sellingPrice: 200,
    minBatchKg: 3,
    category: "sweets",
    state: "Haryana",
    season: "winter",
    availability: "pre-order",
    imageUrl: "/assets/generated/product-churma-ladoo-haryana.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 1,
    name: "Moong Dal Halwa",
    description:
      "Haryana ki rasoi ka raaja — moong dal ka halwa. Ghee ki khushboo, doodh ki richness, saffron ki shaan. Ek baar kha lo toh saal bhar yaad rahega.",
    ingredients: [
      "Dhuli Moong Dal (Split Green Gram)",
      "Desi Ghee",
      "Full Fat Doodh (Milk)",
      "Chini",
      "Kesar (Saffron)",
      "Elaichi",
      "Badam",
      "Pista",
    ],
    preparationMethod:
      "Dal soaked 6 hours, coarsely ground. Slow-roasted in ghee 2 hours. Milk added gradually, stirred continuously. Saffron and nuts added at end.",
    usp: "Takes 3+ hours to make correctly — this is why no one does it anymore. Babita ji's proportion gives perfectly dry, non-greasy halwa. Winter-only delicacy.",
    mrp: 380,
    sellingPrice: 300,
    minBatchKg: 3,
    category: "sweets",
    state: "Haryana",
    season: "winter",
    availability: "pre-order",
    imageUrl: "/assets/generated/product-moong-halwa-haryana.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 1,
    name: "Bajre ki Khichdi Masala",
    description:
      "Haryana ka asli winter food — bajre ki khichdi ka ready masala mix. Ghar mein banao, khichdi ready in 20 minutes, swaad poora Haryanvi. Gaon waali feeling!",
    ingredients: [
      "Bajra (Pearl Millet)",
      "Jeera",
      "Ajwain",
      "Hing",
      "Haldi",
      "Lal Mirch",
      "Dhania",
      "Methi Dana",
    ],
    preparationMethod:
      "Each spice individually dry-roasted at different temperatures. Stone-ground in traditional chakki. Mixed in exact proportions. Packed in airtight container.",
    usp: "Bajra is a superfood — iron-rich, cooling in summer, warming in winter. Babita ji's masala uses Hisar bajra, famous for best flavour.",
    mrp: 140,
    sellingPrice: 110,
    minBatchKg: 2,
    category: "masala",
    state: "Haryana",
    season: "winter",
    availability: "pre-order",
    imageUrl: "/assets/generated/product-bajra-ladoo-haryana.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 1,
    name: "Kachri Ki Chutney",
    description:
      "Haryana ka secret weapon — kachri ki khatti-meethi chutney. Wild desert melon, sun-dried aur pees ke bani. Dal chawal ke saath lagao, khaana ek aur level pe jata hai.",
    ingredients: [
      "Kachri (Wild Desert Melon)",
      "Jeera",
      "Dhania Powder",
      "Lal Mirch",
      "Amchur",
      "Namak",
      "Hing",
    ],
    preparationMethod:
      "Kachri sun-dried for 5 days. Dry-roasted with spices. Stone-ground to coarse chutney powder. Can be used dry or mixed with water/curd.",
    usp: "Kachri grows wild in Haryana's semi-arid land — zero farming effort, 100% natural. A lost condiment being revived by Babita ji. Rare in urban markets.",
    mrp: 160,
    sellingPrice: 120,
    minBatchKg: 2,
    category: "chutney",
    state: "Haryana",
    season: "summer",
    availability: "seasonal",
    imageUrl:
      "/assets/generated/product-kachri-chutney-haryana.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 1,
    name: "Singri Ki Sabzi (Dried)",
    description:
      "Haryana ki gaanv wali sabzi — field beans ki dried pickle-style preparation. Sadiyon se gharon mein banti hai. Sardiyon mein roti ke saath yeh lagao, poori duniya bhool jaoge.",
    ingredients: [
      "Sangri (Dried Field Beans)",
      "Sarson ka Tel",
      "Hing",
      "Jeera",
      "Lal Mirch",
      "Amchur",
      "Haldi",
    ],
    preparationMethod:
      "Sangri soaked overnight, boiled lightly. Spiced and slow-cooked in mustard oil. Spread on cloth, sun-dried 2 days. Achieves unique semi-dry texture.",
    usp: "A Haryana village exclusive — almost impossible to find in cities. High protein, preservative-free. Stays fresh 6 months. Babita ji's version uses heirloom sangri variety.",
    mrp: 200,
    sellingPrice: 160,
    minBatchKg: 3,
    category: "achar",
    state: "Haryana",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-singri-haryana.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 1,
    name: "Bajra Ladoo",
    description:
      "Haryana ki jaan — bajra ke ladoo. Thand mein khaao, shareer ko garam rakhte hain. Dadi ke zamaane se aayi yeh recipe — ab Babita Tai ke haathon mein hai.",
    ingredients: [
      "Bajra Aatta (Pearl Millet Flour)",
      "Gurh",
      "Desi Ghee",
      "Elaichi",
      "Til",
      "Gond (Edible Gum)",
    ],
    preparationMethod:
      "Bajra flour roasted in ghee 45 mins. Gond fried separately, ground. All mixed with jaggery while warm. Rolled into ladoos, set for 1 hour.",
    usp: "Gond (edible gum) adds joint-strengthening properties — traditional winter health food. Especially good for new mothers. Babita ji's ladoos are known for perfect binding.",
    mrp: 240,
    sellingPrice: 190,
    minBatchKg: 3,
    category: "sweets",
    state: "Haryana",
    season: "winter",
    availability: "pre-order",
    imageUrl: "/assets/generated/product-bajra-ladoo-haryana.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 1,
    name: "Namkeen Mathri (Ajwain)",
    description:
      "Masaledar, khasta, crispy — Haryana ki namkeen mathri chai ke saath waisa hi lagti hai jaise jodi banana ke liye hi bani ho. Babita Tai ki haath ki kalaakari.",
    ingredients: [
      "Gehun Aatta",
      "Ajwain",
      "Kaala Jeera",
      "Desi Ghee",
      "Kaala Namak",
      "Kali Mirch",
      "Hing",
    ],
    preparationMethod:
      "Hard dough with ghee and whole spices. Rolled to 3mm. Pricked with fork 20 times per piece. Deep-fried on medium heat 8-10 mins per batch.",
    usp: "Ajwain aids digestion — this is a snack that's also a digestive. Babita ji's mathri uses double the normal ghee ratio for extra crispness.",
    mrp: 160,
    sellingPrice: 130,
    minBatchKg: 3,
    category: "snacks",
    state: "Haryana",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-namakpara.dim_600x500.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 1,
    name: "Gajar Gobhi Shalgam Achar",
    description:
      "Haryana ki sardiyon ka achar — gajar, gobhi, shalgam. Mixed sabzi ka achar jo ek baar khaao toh poori thali saaf ho jaaye. Dadi ke haath waala swaad!",
    ingredients: [
      "Gajar (Carrot)",
      "Gobhi (Cauliflower)",
      "Shalgam (Turnip)",
      "Sarson ka Tel",
      "Lal Mirch",
      "Methi Dana",
      "Haldi",
      "Namak",
    ],
    preparationMethod:
      "Vegetables cut in thick pieces, salted overnight to remove water. Spice paste made with mustard oil. Vegetables coated well. Sun-cured 5-7 days.",
    usp: "Seasonal winter achar — made only Nov to Feb when vegetables are at peak. No water content = no spoilage. Babita ji's version stays good for 8 months.",
    mrp: 180,
    sellingPrice: 140,
    minBatchKg: 4,
    category: "achar",
    state: "Haryana",
    season: "winter",
    availability: "pre-order",
    imageUrl: "/assets/generated/product-mixed-veg-pickle.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 1,
    name: "Halwa Paratha Mix (Haryanvi)",
    description:
      "Sunday morning special — Haryanvi halwa paratha ka ready mix. Sirf ghee aur paani chahiye. Baaki sab Babita Tai ne kar diya. Subah uthke 15 minute mein nashta ready.",
    ingredients: [
      "Gehun Aatta",
      "Sooji (Semolina)",
      "Gurh Powder",
      "Ghee",
      "Saunf",
      "Elaichi",
    ],
    preparationMethod:
      "Atta and sooji blended in exact ratio. Gurh powder and spices mixed dry. Each ingredient weighed precisely. Packed in separate compartments.",
    usp: "Two-in-one combo pack — halwa and paratha from same base. Haryana village breakfast, ready in 15 mins. Babita ji's mix ensures no lumps in halwa.",
    mrp: 200,
    sellingPrice: 160,
    minBatchKg: 3,
    category: "masala",
    state: "Haryana",
    season: "winter",
    availability: "available-today",
    imageUrl: "/assets/generated/product-namakpara.dim_600x500.jpg",
    isAvailable: true,
  },

  // ============================================================
  // PUNJAB — 10 Products (makerIndex: 3 = Preetkaur Aunty)
  // ============================================================
  {
    makerIndex: 3,
    name: "Amritsari Aam Ka Achar",
    description:
      "Amritsar se sidha — Preetkaur Aunty ka mango pickle. Sarson ka tel, kali mirch, saunf — panj tarkibon wala Punjabi achar. Roti ke saath? Waheguru!",
    ingredients: [
      "Kacchi Keri (Raw Mango)",
      "Sarson ka Tel (Mustard Oil)",
      "Saunf (Fennel)",
      "Kalonji (Nigella)",
      "Methi Dana",
      "Lal Mirch",
      "Namak",
      "Haldi",
    ],
    preparationMethod:
      "Mangoes cut in chunks, salted overnight. Mustard oil heated to smoking, cooled. All spices added to cooled oil. Mango packed in jars with spiced oil poured over. Sun-cured 30 days.",
    usp: "Extra-spicy Punjabi tradition — Preetkaur ji uses sarson oil from local kohlus (oil press). Whole spices, no powder. The pickle improves with age.",
    mrp: 250,
    sellingPrice: 190,
    minBatchKg: 5,
    category: "achar",
    state: "Punjab",
    season: "summer",
    availability: "seasonal",
    imageUrl: "/assets/generated/product-achar.dim_600x500.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 3,
    name: "Pinni (Punjab's Winter Superfood)",
    description:
      "Punjab ki sardi ka lifeline — gehun aata, gurh, ghee aur gond ka pinni. Dadi ne di thi nai maa ko, Preetkaur Aunty ne aaj tujhe de di. Pyaar ka dose.",
    ingredients: [
      "Gehun Aatta",
      "Gurh (Jaggery)",
      "Desi Ghee",
      "Gond (Edible Gum)",
      "Badam",
      "Khopra (Coconut)",
      "Elaichi",
      "Khas Khas",
    ],
    preparationMethod:
      "Flour slow-roasted in ghee 2 hours. Gond fried, ground. Gurh melted to thick syrup. All combined while warm. Hand-shaped into rounds. Set 4 hours.",
    usp: "Traditional postpartum food — given to new mothers for strength. Gond heals joints. Preetkaur ji makes pinni exactly as her dadi's recipe — no shortcuts.",
    mrp: 340,
    sellingPrice: 270,
    minBatchKg: 3,
    category: "sweets",
    state: "Punjab",
    season: "winter",
    availability: "pre-order",
    imageUrl: "/assets/generated/product-pinni-punjab.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 3,
    name: "Gajak (Sesame Jaggery Brittle)",
    description:
      "Lohri ka gajak — jab yeh toot-toot ke muh mein jaata hai, toh Lohri ki yaad aa jaati hai. Preetkaur Aunty ka gajak — til, gurh, ghee — simple mein highest class.",
    ingredients: ["Til (Sesame)", "Gurh (Jaggery)", "Desi Ghee", "Elaichi"],
    preparationMethod:
      "Sesame toasted golden. Jaggery cooked to hard-crack stage (160°C). Ghee and sesame mixed in rapidly. Poured on greased stone, rolled thin, cut while warm.",
    usp: "Lohri season delicacy — iron-rich, calcium-rich. Preetkaur ji's gajak uses single-source til from Barnala farms. Cracks perfectly, no stickiness.",
    mrp: 300,
    sellingPrice: 240,
    minBatchKg: 3,
    category: "sweets",
    state: "Punjab",
    season: "winter",
    availability: "festival-special",
    imageUrl: "/assets/generated/product-gajak-punjab.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 3,
    name: "Punjabi Mathri",
    description:
      "Chai ke saath mathri — yeh jodi sabse purani hai. Ghee mein tali, ajwain-kali mirch wali mathri. Preetkaur Aunty ki mathri ek baar khi toh packet band nahin hoga.",
    ingredients: [
      "Maida",
      "Desi Ghee",
      "Ajwain",
      "Kali Mirch",
      "Namak",
      "Hing",
    ],
    preparationMethod:
      "Stiff dough with ghee (moyan). Rested 30 mins. Rolled to coin thickness. Poked all over. Fried on low-medium heat until evenly golden and completely crisp.",
    usp: "Pure maida, pure ghee — the original recipe. Preetkaur ji refuses to use dalda or refined oil. Her mathri is famous in three gullies of Amritsar.",
    mrp: 180,
    sellingPrice: 140,
    minBatchKg: 3,
    category: "snacks",
    state: "Punjab",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-namakpara.dim_600x500.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 3,
    name: "Mango Chunda (Sweet Mango Pickle)",
    description:
      "Jab achar sweet ho — Punjab style chunda. Kacchi keri ko gurh mein boil karke banayi mithi-khatti chutney jaise achar. Paratha ke saath? Waheguru G!",
    ingredients: [
      "Kacchi Keri (Raw Mango)",
      "Gurh",
      "Lal Mirch",
      "Saunf",
      "Haldi",
      "Namak",
    ],
    preparationMethod:
      "Mangoes grated coarse. Mixed with salt, dried in sun 2 days. Jaggery syrup made and combined with mango. Spices added. Sun-set for 1 week.",
    usp: "Sweet-tangy contrast — popular with kids. Preserves naturally due to jaggery and sun-curing. Preetkaur ji's chunda uses Rawalpindi-style Punjabi recipe from her nani.",
    mrp: 220,
    sellingPrice: 170,
    minBatchKg: 4,
    category: "achar",
    state: "Punjab",
    season: "summer",
    availability: "seasonal",
    imageUrl: "/assets/generated/product-mango-chunda-punjab.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 3,
    name: "Amritsari Wadi",
    description:
      "Wadi wala rassa — Punjab ki pehchaan. Preetkaur Aunty ki ghar ki wadi — moong dal, urad dal, masale — sun-dried to perfection. Dal mein daalo, khushboo poore ghar mein.",
    ingredients: [
      "Moong Dal",
      "Urad Dal",
      "Heeng",
      "Jeera",
      "Kaali Mirch",
      "Saunf",
      "Lal Mirch",
      "Namak",
    ],
    preparationMethod:
      "Dals soaked, ground to thick batter with spices. Piped into small nuggets on cloth. Sun-dried 4-5 days until completely dry and hard.",
    usp: "Dal wadi is Punjab's original protein supplement. Preetkaur ji makes them only in winter — summer humidity ruins the drying process. Stays 1 year.",
    mrp: 200,
    sellingPrice: 160,
    minBatchKg: 2,
    category: "snacks",
    state: "Punjab",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-wadi-punjab.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 3,
    name: "Aam Papad (Mango Leather)",
    description:
      "Bachpan ka swaad — aam papad. Ghar ki chat pe sookha, meetha-khatta, chewy mango leather. Preetkaur Aunty ka aam papad aapko woh gali, woh chat, woh dhoop yaad dilayega.",
    ingredients: [
      "Alphonso/Dashehari Aam (Mango)",
      "Gurh",
      "Namak",
      "Elaichi",
      "Kala Namak",
    ],
    preparationMethod:
      "Ripe mangoes peeled, pulped smooth. Mixed with jaggery and spices. Spread thin on plastic sheets. Sun-dried 3-4 days till firm. Cut in strips.",
    usp: "Only seasonal — made April-May when mangoes are at peak sweetness. Preetkaur ji uses Malihabad mango pulp for best flavour. No artificial colour.",
    mrp: 180,
    sellingPrice: 140,
    minBatchKg: 2,
    category: "snacks",
    state: "Punjab",
    season: "summer",
    availability: "seasonal",
    imageUrl: "/assets/generated/product-aam-papad-punjab.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 3,
    name: "Besan Ka Halwa (Karahi Wala)",
    description:
      "Kaali karahi mein ghee, besan aur doodh — Punjab ka ghar ghar ka comfort food. Gurh ki meethas, doodh ki richness. Ek bowl khao, sab thakaan door ho jaaye.",
    ingredients: [
      "Besan (Gram Flour)",
      "Desi Ghee",
      "Doodh (Full Cream Milk)",
      "Gurh",
      "Elaichi",
      "Badam",
      "Kesar",
    ],
    preparationMethod:
      "Besan dry-roasted in ghee on medium heat 40 mins until deep golden and fragrant. Milk added carefully in batches. Jaggery added, stirred till thick. Nuts garnished.",
    usp: "Protein + good fats = traditional energy food. Preetkaur ji's besan halwa is made in her daadi's lohey ki karahi — she says the iron vessel changes the taste.",
    mrp: 340,
    sellingPrice: 270,
    minBatchKg: 3,
    category: "sweets",
    state: "Punjab",
    season: "winter",
    availability: "pre-order",
    imageUrl: "/assets/generated/product-besan-halwa-punjab.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 3,
    name: "Amritsari Papad (Hand-rolled)",
    description:
      "Ghar ki daawat ho ya roz ka khaana — Preetkaur Aunty ka haath se bela hua papad. Urad dal, kali mirch, namak — teen cheezein mein ek zabardast swaad.",
    ingredients: [
      "Urad Dal",
      "Kali Mirch",
      "Namak",
      "Jeera",
      "Hing",
      "Papad Khar",
    ],
    preparationMethod:
      "Dal soaked, ground very fine. Mixed with spices and papad khar. Rolled paper-thin with wooden belan. Sun-dried on banana leaf on rooftop.",
    usp: "Hand-rolled papads are 3x thinner than machine-made — they fry crispier. Preetkaur ji rolls 200 papads per day. Solar-dried on her Amritsar terrace.",
    mrp: 160,
    sellingPrice: 120,
    minBatchKg: 2,
    category: "snacks",
    state: "Punjab",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-papad-punjab.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 3,
    name: "Sarson Ka Saag Masala Mix",
    description:
      "Winter special — Preetkaur Aunty ka saag masala mix. Bas makki ki roti banao aur yeh mix daal ke pakao — Punjab ki barsaat wali raat ka swaad ghar mein aa jaayega.",
    ingredients: [
      "Sarson Dana (Mustard Seeds)",
      "Methi Dana",
      "Dhania",
      "Jeera",
      "Hing",
      "Lal Mirch",
      "Haldi",
      "Amchur",
      "Kasoori Methi",
    ],
    preparationMethod:
      "Each spice slow dry-roasted individually. Stone-ground in traditional chakki to coarse powder. Blended in exact proportion Preetkaur ji's daadi used.",
    usp: "Reduces saag-making time by 50%. Preetkaur ji's blend is the exact spice ratio for Amritsari-style saag. Stone-ground = better aroma than machine-ground.",
    mrp: 150,
    sellingPrice: 110,
    minBatchKg: 2,
    category: "masala",
    state: "Punjab",
    season: "winter",
    availability: "pre-order",
    imageUrl: "/assets/generated/product-saag-masala-punjab.dim_800x600.jpg",
    isAvailable: true,
  },

  // ============================================================
  // UTTAR PRADESH — 10 Products (makerIndex: 2 = Sarla Maasi)
  // ============================================================
  {
    makerIndex: 2,
    name: "Agra Petha (Kesar-Elaichi)",
    description:
      "Agra ke Taj Mahal jaisi mashoor — petha mithaai. Translucent, melt-in-mouth, kesar ki khushboo. Sarla Maasi ki petha khao toh lagta hai Agra pahunch gaye.",
    ingredients: [
      "Ash Gourd (Petha)",
      "Chini (Sugar)",
      "Kesar (Saffron)",
      "Elaichi (Cardamom)",
      "Chuna (Lime for setting)",
    ],
    preparationMethod:
      "Ash gourd peeled, poked with fork, rubbed with lime water. Blanched, sugar syrup cooked to thread consistency. Gourd soaked 24 hrs. Flavoured. Sun-dried.",
    usp: "GI-tagged Agra Petha — world famous. Sarla Maasi learnt from a 3rd-generation Agra petha maker. Her kesar version is lighter and less sweet than commercial brands.",
    mrp: 280,
    sellingPrice: 220,
    minBatchKg: 3,
    category: "sweets",
    state: "Uttar Pradesh",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-petha-agra-up.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 2,
    name: "Nimbu Ka Achar (Oil-Free)",
    description:
      "UP ka sabse healthy achar — nimbu, namak, masale aur dhoop. Koi tel nahin. Sarla Maasi ka nuskhaa decades purana hai. Liver ke liye best, swaad mein best.",
    ingredients: [
      "Kagzi Nimbu (Thin-skinned Lemon)",
      "Kala Namak",
      "Kali Mirch",
      "Hing",
      "Saunf",
      "Ajwain",
      "Lal Mirch",
    ],
    preparationMethod:
      "Lemons quartered, salted generously. Kept in sun-exposed clay pot 30 days. Spices added at day 15. Shaken daily. Oil-free, fermentation-preserved.",
    usp: "Zero oil — naturally preserved by salt and acidity. Probiotic benefits from fermentation. Sarla Maasi's lemons come from Varanasi orchards — thinner skin, better brine.",
    mrp: 180,
    sellingPrice: 140,
    minBatchKg: 4,
    category: "achar",
    state: "Uttar Pradesh",
    season: "summer",
    availability: "seasonal",
    imageUrl: "/assets/generated/product-achar.dim_600x500.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 2,
    name: "Besan Ladoo (Lucknawi)",
    description:
      "Lucknow ka andaaz — besan ladoo mein bhi. Barik pisa besan, ghee, chini, pista — Sarla Maasi ki recipe mein ek secret ingredient hai jo woh batati nahin. Khao aur socho!",
    ingredients: [
      "Besan (Fine Gram Flour)",
      "Desi Ghee",
      "Boora (Powdered Sugar)",
      "Elaichi",
      "Pista",
      "Badam",
      "Kesar",
    ],
    preparationMethod:
      "Besan slow-roasted in ghee 1.5 hours on minimum flame. Cooled to warm. Sugar added, mixed. Elaichi and nuts folded in. Hand-rolled while still warm.",
    usp: "Lucknow's nawabi influence — fine texture, not coarse. Sarla Maasi uses boora (powdered sugar) not chini for melt-in-mouth quality. 30% more ghee than standard recipe.",
    mrp: 300,
    sellingPrice: 240,
    minBatchKg: 3,
    category: "sweets",
    state: "Uttar Pradesh",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-besan-ladoo-up.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 2,
    name: "Gajar Ka Halwa (Mathura Style)",
    description:
      "Sardi aayi nahi aur Sarla Maasi ki gajar halwa order aa gayi! Laal gajar, pure ghee, doodh — yeh halwa factory wale kisi bhi keemat mein nahin bana sakte.",
    ingredients: [
      "Desi Gajar (Red Winter Carrot)",
      "Full Cream Doodh",
      "Desi Ghee",
      "Chini",
      "Elaichi",
      "Kesar",
      "Badam",
      "Kaju",
      "Khoya",
    ],
    preparationMethod:
      "Carrots grated fine. Cooked in milk 2 hours until milk absorbed. Ghee added, roasted golden. Sugar, khoya added. Cooked till thickened. Nuts and saffron garnished.",
    usp: "Seasonal — made only Jan-Feb with red UP winter carrots. Red gajar has more beta-carotene than orange. Sarla Maasi's recipe uses equal weight carrot and milk.",
    mrp: 380,
    sellingPrice: 300,
    minBatchKg: 3,
    category: "sweets",
    state: "Uttar Pradesh",
    season: "winter",
    availability: "pre-order",
    imageUrl: "/assets/generated/product-gajar-halwa-up.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 2,
    name: "Mathura Peda",
    description:
      "Mathura prasad ghar mein — kesar peda. Khoya ki richness, saffron ki rang, elaichi ki khushboo. Sarla Maasi ki peda khao aur bhagwan yaad aayenge.",
    ingredients: [
      "Khoya (Mawa)",
      "Chini",
      "Kesar",
      "Elaichi",
      "Pista",
      "Badam Flakes",
    ],
    preparationMethod:
      "Khoya freshly made from full-fat milk. Cooked with sugar till slightly golden. Kesar milk added. Cooled. Shaped in round disc with thumbprint. Nut garnished.",
    usp: "Mathura peda is distinct from other pedas — darker, slightly caramelised khoya. Sarla Maasi visits Mathura to source fresh khoya from gau-shala milk.",
    mrp: 320,
    sellingPrice: 260,
    minBatchKg: 3,
    category: "sweets",
    state: "Uttar Pradesh",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-peda-up.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 2,
    name: "Khasta Kachori",
    description:
      "Lucknow ki subah — chai aur khasta kachori. Moong dal bhurji andar, maida ki crispy shell — yeh kachori thodi der baad bhi khasta rehti hai. Magic? Nahin, recipe.",
    ingredients: [
      "Maida",
      "Moong Dal",
      "Desi Ghee",
      "Hing",
      "Saunf",
      "Jeera",
      "Lal Mirch",
      "Amchur",
    ],
    preparationMethod:
      "Stiff maida dough with ghee. Filling made of coarsely-ground soaked moong, spiced, dried. Stuffed, sealed tightly. Fried on slow heat 12-15 mins.",
    usp: "Stays crispy 12+ hours — Sarla Maasi's secret is the exact moisture content of filling. These are courier-safe, unlike most kachoris.",
    mrp: 160,
    sellingPrice: 120,
    minBatchKg: 3,
    category: "snacks",
    state: "Uttar Pradesh",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-namakpara.dim_600x500.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 2,
    name: "Amla Murabba",
    description:
      "Dadi ki divinity — amla murabba. Sugar mein bharke amle, saal bhar ke liye. Subah khali pet ek amla — doctor se door, energy se paas. Sarla Maasi ki recipe — 50 saal purani.",
    ingredients: [
      "Amla (Indian Gooseberry)",
      "Chini (Sugar)",
      "Kesar",
      "Elaichi",
      "Laung (Clove)",
      "Dalchini",
    ],
    preparationMethod:
      "Amla pricked all over with fork. Blanched briefly. Soaked in alum water overnight to firm up. Cooked in thick sugar syrup with spices. Sun-dried 2 days.",
    usp: "Highest Vitamin C in any Indian preserve. Sarla Maasi sources Pratapgarh amla (famous UP variety). Her murabba method preserves maximum nutrition vs commercial versions.",
    mrp: 280,
    sellingPrice: 220,
    minBatchKg: 3,
    category: "achar",
    state: "Uttar Pradesh",
    season: "winter",
    availability: "pre-order",
    imageUrl: "/assets/generated/product-murabba-up.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 2,
    name: "Kanji (Black Carrot Probiotic Drink)",
    description:
      "UP ki sardi ki dawai — kaali gajar ki kanji. Probiotic, tangy, gut-healing drink. Subah ek glass, sehat mast. Sarla Maasi ki kanji poore mohalle mein famous hai.",
    ingredients: [
      "Kaali Gajar (Black Carrot)",
      "Sarson Dana (Mustard Seeds)",
      "Kaala Namak",
      "Lal Mirch",
      "Namak",
      "Heeng",
    ],
    preparationMethod:
      "Black carrots cut in sticks. Mustard seeds coarsely ground. Vegetables and mustard placed in clay pot with water. Fermented in sun 3-5 days, stirred daily.",
    usp: "Probiotic drink — natural fermentation. Anthocyanin in black carrots = antioxidant. Sarla Maasi provides in sealed glass jar. Stays 2 weeks refrigerated.",
    mrp: 160,
    sellingPrice: 130,
    minBatchKg: 2,
    category: "chutney",
    state: "Uttar Pradesh",
    season: "spring",
    availability: "pre-order",
    imageUrl: "/assets/generated/product-kanji-up.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 2,
    name: "Aloo Ka Achar (UP Tehzeeb)",
    description:
      "Roti ke saath, parathe ke saath, chawal ke saath — aloo ka achar sab ke saath fit. Sarla Maasi ka Lucknawi andaaz — masaledar, khatta, slightly meetha. Nawabi touch!",
    ingredients: [
      "Aloo (Potato)",
      "Sarson ka Tel",
      "Methi Dana",
      "Hing",
      "Lal Mirch",
      "Haldi",
      "Amchur",
      "Saunf",
      "Kalonji",
    ],
    preparationMethod:
      "Potatoes boiled al-dente, dried completely. Spice paste made with mustard oil. Potatoes tossed in spice paste. Sun-cured 3 days until spices penetrate completely.",
    usp: "Potato pickle is UP specialty — rarely made commercially. Sarla Maasi's version uses whole jeera and saunf seeds for extra bite. Shelf-stable for 3 months.",
    mrp: 160,
    sellingPrice: 130,
    minBatchKg: 4,
    category: "achar",
    state: "Uttar Pradesh",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-aloo-achar-up.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 2,
    name: "Namak Pare",
    description:
      "Diwali wale namak pare — maida, ajwain, ghee. Khasta, crispy, namkeen. Ek khaya toh band nahin hoga. Sarla Maasi teen generations se banati aa rahi hain.",
    ingredients: [
      "Maida",
      "Desi Ghee",
      "Ajwain",
      "Namak",
      "Kali Mirch",
      "Hing",
    ],
    preparationMethod:
      "Stiff dough with ghee and ajwain. Rolled thin. Cut in diamond shapes. Deep-fried on medium heat until golden, crisp throughout.",
    usp: "Diwali special traditionally — but Sarla Maasi makes year-round due to demand. Uses zero refined oil — pure ghee only. Stays fresh 4 weeks.",
    mrp: 150,
    sellingPrice: 120,
    minBatchKg: 3,
    category: "snacks",
    state: "Uttar Pradesh",
    season: "all-season",
    availability: "available-today",
    imageUrl: "/assets/generated/product-namakpara.dim_600x500.jpg",
    isAvailable: true,
  },

  // ============================================================
  // UTTARAKHAND — 10 Products (makerIndex: 4 = Geeta Devi)
  // ============================================================
  {
    makerIndex: 4,
    name: "Buransh Ka Sharbat (Rhododendron Syrup)",
    description:
      "Pahad ki pehchaan — buransh ke phool se bana laal sharbat. April mein Himalaya ke jangalon mein khilte buransh se Geeta Devi ji yeh khazana banati hain. Ek sip — pahad yaad aa gaya.",
    ingredients: [
      "Buransh Phool (Rhododendron Flowers)",
      "Gurh (Jaggery)",
      "Nimbu Ras",
      "Kali Mirch",
      "Sendha Namak",
    ],
    preparationMethod:
      "Buransh flowers hand-picked at dawn, washed. Boiled with jaggery to syrup consistency. Lemon juice added as preservative. Strained, bottled. Only April-May.",
    usp: "Seasonal — available only 6 weeks/year. High in Vitamin C and antioxidants. Geeta ji hikes 3km to harvest flowers. Anti-hypertensive properties researched by AIIMS Rishikesh.",
    mrp: 320,
    sellingPrice: 260,
    minBatchKg: 2,
    category: "chutney",
    state: "Uttarakhand",
    season: "summer",
    availability: "seasonal",
    imageUrl:
      "/assets/generated/product-buransh-syrup-uttarakhand.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 4,
    name: "Bhang Ki Chutney (Hemp Seed)",
    description:
      "Pahad ka superfoods — bhang ki chutney. Uttarakhand ke pahadon se aayi yeh chutney rice ke saath khao toh Geeta Devi ji ke gaon Almora ki hawa aayi lagti hai.",
    ingredients: [
      "Bhang Ke Beej (Hemp Seeds)",
      "Hari Mirch",
      "Lahsun (Garlic)",
      "Nimbu Ras",
      "Dhania Patta",
      "Namak",
      "Hing",
    ],
    preparationMethod:
      "Hemp seeds lightly dry-roasted. Stone-ground with raw garlic and green chili. Lemon juice and salt added. Fresh herbs folded in. No heat after adding lemon.",
    usp: "Legal hemp — contains omega-3, omega-6, protein. Uttarakhand's oldest condiment. Geeta ji stone-grinds on her sil-batta (grinding stone) from 1970.",
    mrp: 180,
    sellingPrice: 140,
    minBatchKg: 2,
    category: "chutney",
    state: "Uttarakhand",
    season: "all-season",
    availability: "available-today",
    imageUrl:
      "/assets/generated/product-gahat-chutney-uttarakhand.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 4,
    name: "Bal Mithai (Kumaoni Chocolate)",
    description:
      "Almora ki shan — bal mithai. Dark khoya ki barfi with white sugar balls on top. Chocolatey, rich, melt-in-mouth. India ka indigenous chocolate — kisi ne khaya hai kya?",
    ingredients: [
      "Khoya (Mawa)",
      "Chini",
      "Kesar",
      "Koate Chini (Sugar Balls)",
      "Elaichi",
    ],
    preparationMethod:
      "Khoya cooked with sugar on slow flame 2 hours until deep caramel-brown. Cooled. Cut in blocks. Pressed with white sugar ball coating on all sides.",
    usp: "GI-tagged Uttarakhand sweet — unique in India. The deep caramelisation of khoya creates natural chocolate-like flavour. Geeta ji gets khoya from Almora's famous dairy.",
    mrp: 320,
    sellingPrice: 260,
    minBatchKg: 3,
    category: "sweets",
    state: "Uttarakhand",
    season: "all-season",
    availability: "available-today",
    imageUrl:
      "/assets/generated/product-bal-mithai-uttarakhand.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 4,
    name: "Jhangora Ki Kheer (Barnyard Millet)",
    description:
      "Pahadi superfood — jhangora ki kheer. Himalayan barnyard millet, doodh, gurh — yeh kheer digestive aur nutritious hai. Geeta Devi ji ki recipe generations se chali aa rahi hai.",
    ingredients: [
      "Jhangora (Barnyard Millet)",
      "Full Cream Doodh",
      "Gurh",
      "Elaichi",
      "Kesar",
      "Badam",
      "Khopra",
    ],
    preparationMethod:
      "Jhangora washed, soaked 2 hours. Cooked in milk on slow fire 1.5 hours, stirring continuously. Jaggery added, cooked further. Coconut and nuts added at end.",
    usp: "Jhangora has the lowest glycemic index of all millets. Grown only in Uttarakhand hills above 1200m. Geeta ji's variety is organically grown on her family terrace farm.",
    mrp: 260,
    sellingPrice: 210,
    minBatchKg: 2,
    category: "sweets",
    state: "Uttarakhand",
    season: "monsoon",
    availability: "pre-order",
    imageUrl:
      "/assets/generated/product-jhangora-kheer-uttarakhand.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 4,
    name: "Gahat Dal Ki Chutney (Horse Gram)",
    description:
      "Pahad ki jaan — gahat ki chutney. Stone-ground horsegram with mountain herbs. UP-Bihar wale dal samjhenge nahin — yeh pahadi magic hai. Roti ke saath lagao, subah full energy.",
    ingredients: [
      "Gahat Dal (Horse Gram)",
      "Hari Mirch",
      "Lahsun",
      "Jakhiya Seeds",
      "Til",
      "Nimbu",
      "Dhania",
      "Namak",
    ],
    preparationMethod:
      "Horse gram soaked overnight, partially cooked. Jakhiya seeds (pahadi tempering spice) roasted separately. Stone-ground together with raw garlic and herbs.",
    usp: "Jakhiya is a rare Uttarakhand spice — unavailable outside hills. Gahat has highest protein of all dals. Geeta ji grows gahat on her terrace farm at 1400m altitude.",
    mrp: 200,
    sellingPrice: 160,
    minBatchKg: 2,
    category: "chutney",
    state: "Uttarakhand",
    season: "winter",
    availability: "pre-order",
    imageUrl:
      "/assets/generated/product-gahat-chutney-uttarakhand.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 4,
    name: "Timru Ka Achar (Pahadi Pepper)",
    description:
      "Pahadi kali mirch — timru. Uttarakhand jungle ka masala — wild berries, mustard oil, pahadi mirch. Yeh achar khane wale doosre achar bhool jaate hain. One of a kind.",
    ingredients: [
      "Timru Beej (Wild Himalayan Prickly Ash)",
      "Sarson ka Tel",
      "Lal Pahadi Mirch",
      "Namak",
      "Hing",
      "Haldi",
    ],
    preparationMethod:
      "Timru berries hand-picked in autumn, dried. Cracked slightly to release aroma. Mixed with mustard oil and pahadi spices. Rested 10 days before bottling.",
    usp: "Timru grows only above 1800m in Himalayan forests — zero cultivation. Wild-harvested by Geeta ji's family. Numbing, citrusy, pepper-like flavour — nothing else like it in India.",
    mrp: 250,
    sellingPrice: 200,
    minBatchKg: 2,
    category: "achar",
    state: "Uttarakhand",
    season: "all-season",
    availability: "available-today",
    imageUrl:
      "/assets/generated/product-timru-pickle-uttarakhand.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 4,
    name: "Pahadi Aloo Ki Chips",
    description:
      "Pahadi aloo — chota, tight, masaledar. Geeta Devi ji ke gaon ke khet se seedha. Sun-dried aloo chips with mountain masala — yeh chips khao toh factory chips khaana band ho jaayega.",
    ingredients: [
      "Pahadi Aloo (Mountain Potato)",
      "Rock Salt",
      "Pahadi Mirch",
      "Jakhiya",
      "Nimbu Ras",
      "Haldi",
    ],
    preparationMethod:
      "Small mountain potatoes sliced thin on mandoline. Dipped in salted lemon water. Sun-dried on bamboo mats for 2 days. Fried in fresh mustard oil.",
    usp: "Pahadi aloo are naturally more flavourful — grown at altitude with mineral-rich water. Geeta ji's chips are crunchier because mountain potatoes have less moisture.",
    mrp: 200,
    sellingPrice: 160,
    minBatchKg: 2,
    category: "snacks",
    state: "Uttarakhand",
    season: "all-season",
    availability: "available-today",
    imageUrl:
      "/assets/generated/product-pahadi-chips-uttarakhand.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 4,
    name: "Singal (Pahadi Fried Bread Snack)",
    description:
      "Pahadi festival food — singal. Urad dal aur chawal se bana yeh fried bread Geeta ji ke ghar mein tyohaaron pe banta hai. Crispy, golden, with mint chutney — heavenly.",
    ingredients: [
      "Urad Dal",
      "Chawal Aata (Rice Flour)",
      "Hing",
      "Ajwain",
      "Namak",
      "Kali Mirch",
    ],
    preparationMethod:
      "Dal soaked 4 hours, ground fine. Mixed with rice flour for structure. Seasoned with ajwain and hing. Piped in lattice pattern on oiled ladle. Deep-fried golden.",
    usp: "Uttarakhand's festive snack — made for Hariyali Teej and Diwali. Gluten-free base (urad + rice). Geeta ji's singal are famous in her Almora block for perfect crunch.",
    mrp: 180,
    sellingPrice: 140,
    minBatchKg: 2,
    category: "snacks",
    state: "Uttarakhand",
    season: "winter",
    availability: "festival-special",
    imageUrl: "/assets/generated/product-namakpara.dim_600x500.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 4,
    name: "Kafal Sharbat (Wild Mountain Cherry Syrup)",
    description:
      "Uttarakhand ka rahasya — kafal! Pahadi wild cherry — reddish-purple, tangy-sweet. Geeta ji isse sharbat banati hain — limited stock, sirf May mein milta hai. Miss mat karo!",
    ingredients: [
      "Kafal (Myrica Esculenta Wild Berries)",
      "Gurh",
      "Nimbu Ras",
      "Kali Namak",
      "Elaichi",
    ],
    preparationMethod:
      "Kafal berries hand-picked at peak ripeness in May. Washed, boiled to extract juice. Mixed with jaggery syrup. Strained through muslin. Lemon added. Bottled.",
    usp: "Kafal is medicinal (traditional use for cough, asthma). Rich in polyphenols. Available only May for 3 weeks. Geeta ji's batch sells out within days of announcement.",
    mrp: 350,
    sellingPrice: 280,
    minBatchKg: 1,
    category: "chutney",
    state: "Uttarakhand",
    season: "summer",
    availability: "seasonal",
    imageUrl:
      "/assets/generated/product-buransh-syrup-uttarakhand.dim_800x600.jpg",
    isAvailable: true,
  },
  {
    makerIndex: 4,
    name: "Pahadi Namak Mix (Himalayan Spice Salt)",
    description:
      "Himalayan se aaya asli pahadi namak — jakhiya, timru, pahadi mirch milaake. Dal chawal pe churao, bas! Khaane ka swaad teen guna. Geeta ji ne teen saal mein yeh blend perfect kiya.",
    ingredients: [
      "Sendha Namak (Rock Salt)",
      "Jakhiya Seeds",
      "Timru Berry Dust",
      "Pahadi Lal Mirch",
      "Dhania Seeds",
      "Ajwain",
    ],
    preparationMethod:
      "Rock salt hand-crushed coarsely. Each spice dry-roasted individually at exact temperature. Blended in small batches. Kept coarse for better flavour release.",
    usp: "Jakhiya + Timru = two hyperlocal Uttarakhand spices in one blend. Zero iodizing, zero anti-caking. Pure mineral salt from Himalayan deposits. Unique in Indian market.",
    mrp: 180,
    sellingPrice: 140,
    minBatchKg: 2,
    category: "masala",
    state: "Uttarakhand",
    season: "all-season",
    availability: "available-today",
    imageUrl:
      "/assets/generated/product-timru-pickle-uttarakhand.dim_800x600.jpg",
    isAvailable: true,
  },
];
